In [2]:
import torch
from torch import nn

In [3]:
x=torch.randn(100,3)
layer=nn.Linear(3,5)
print(layer(x).shape)
print(layer.weight)
print(layer.bias)

torch.Size([100, 5])
Parameter containing:
tensor([[ 2.4844e-01, -3.1267e-04, -1.8489e-01],
        [-4.7276e-01,  2.6865e-01, -1.7671e-01],
        [ 8.9830e-02, -2.0662e-01, -1.8330e-01],
        [-8.4731e-03, -1.0417e-01,  1.9441e-01],
        [-5.1064e-01, -4.7218e-01, -3.2646e-01]], requires_grad=True)
Parameter containing:
tensor([-0.2784,  0.4282, -0.4716,  0.0344,  0.1962], requires_grad=True)


In [4]:
x=torch.randn(2,5)
layer=nn.ReLU()
print(layer(x))

tensor([[0.7602, 0.0000, 0.0000, 0.0000, 0.1992],
        [0.0000, 0.0000, 0.0000, 0.6985, 0.0000]])


In [5]:
x = torch.randn(3,7)
drop = nn.Dropout(p=0.3) # p는 죽일 확률
print(drop(x))

tensor([[-0.0649,  0.0000, -0.4968,  0.3990, -0.0618, -0.4768,  0.0000],
        [ 1.5419,  0.0000, -1.9746,  0.0000, -0.9688,  0.0000,  3.5535],
        [-1.2937,  0.0000,  0.4212,  0.2695,  3.4386, -0.7845, -0.4532]])


In [6]:
class sample_model(nn.Module):
    def __init__(self):
        super().__init__()
        self.drop_layer=nn.Sequential(nn.Linear(5,7),
                                      nn.Dropout(p=0.3))

    def forward(self, x):
        x = self.drop_layer(x)
        return x

model=sample_model()
model.train() # train mode로 전환
x=torch.randn(3,5) # 그 담에 x=torch.randn(2,3,5)
print(model(x))

model.eval()
print(model(x)) # test mode

tensor([[-0.4011, -0.0000, -0.0000,  0.4456, -0.2189, -0.2362,  0.0388],
        [ 0.4237,  0.0000,  0.0000,  1.1045, -1.0262, -0.6280,  0.0000],
        [ 1.0467,  0.6808, -0.4255, -0.1392, -1.1525,  0.7598,  1.6455]],
       grad_fn=<MulBackward0>)
tensor([[-0.2808, -0.3936, -0.0294,  0.3119, -0.1532, -0.1653,  0.0271],
        [ 0.2966,  0.6701,  0.4455,  0.7732, -0.7183, -0.4396,  1.4752],
        [ 0.7327,  0.4765, -0.2978, -0.0974, -0.8067,  0.5319,  1.1518]],
       grad_fn=<AddmmBackward0>)


In [7]:
layer = nn.Conv2d(in_channels=1, out_channels=2, kernel_size=3, stride=1, padding=1) # stride=1, padding=0 이 디폴트
layer(torch.randn(32,1,5,5)).shape
# nn,.Linear(3,5) # 채채 # 얘는 채 또는 개체를 원함, 개 x 3
# nn.Conv2d(3,5) # 채채 # 얘는 채행열 또는 개채행열을 원함, 개 x 3 x 행 x 열

torch.Size([32, 2, 5, 5])

In [8]:
layer = nn.Conv2d(3,5,3,stride=2, padding=1)
print(layer(torch.randn(32,3,5,5)).shape)
layer.weight.shape

torch.Size([32, 5, 3, 3])


torch.Size([5, 3, 3, 3])

In [9]:
conv1 = nn.Conv2d(1,8,6, stride=2)
x = torch.randn(32,1,28,28)
print(conv1(x).shape)

conv2 = nn.Conv2d(8,16,3,padding=1)
print(conv2(conv1(x)).shape)

Maxpool = nn.MaxPool2d(kernel_size=2, stride=2) # 채널 개수는 유지
print(Maxpool(conv2(conv1(x))).shape)

torch.Size([32, 8, 12, 12])
torch.Size([32, 16, 12, 12])
torch.Size([32, 16, 6, 6])


In [10]:
maxpool = nn.MaxPool2d(2) # 2 로만 줘도 자동 kernel_size=2, stride=(2,2)
x=torch.randn(1,1,6,6)
print(x)
print(maxpool(x))
print(maxpool(torch.randn(32,3,8,8)).shape)

tensor([[[[ 0.3330, -0.4422, -0.1347,  0.7954,  1.2027,  1.3386],
          [-1.1284,  0.9176, -0.6637, -0.4897, -0.0389,  1.7147],
          [-1.0017, -2.8809, -0.8128,  0.3616,  0.5867, -1.1168],
          [-0.3127,  0.1000, -0.6873,  1.7583, -0.0384,  1.8298],
          [ 0.4372, -1.5508,  1.6971,  0.1306,  0.3447, -0.2234],
          [-0.7665,  0.2764,  0.8106,  2.5216,  0.4991, -1.5788]]]])
tensor([[[[0.9176, 0.7954, 1.7147],
          [0.1000, 1.7583, 1.8298],
          [0.4372, 2.5216, 0.4991]]]])
torch.Size([32, 3, 4, 4])


In [11]:
avgpool=nn.AvgPool2d(2)
x=torch.randn(1,1,6,6)
print(x)
print(avgpool(x))
print(avgpool(torch.randn(32,3,6,6)).shape)

tensor([[[[ 1.4838,  0.1089,  2.5785, -1.2836,  0.7857, -0.1157],
          [-0.9605,  0.4385,  0.9397, -0.0674, -0.6496,  0.2845],
          [ 0.8542,  0.2672,  0.9536,  0.9880,  0.3721,  1.0125],
          [-0.6859,  0.8869, -0.1400, -1.4471, -0.5041,  0.0166],
          [ 0.8669, -2.2924,  1.6720,  2.6076,  0.2229, -0.5814],
          [ 0.8287,  1.2580, -1.9464, -0.9140, -0.8488,  0.7735]]]])
tensor([[[[ 0.2677,  0.5418,  0.0762],
          [ 0.3306,  0.0886,  0.2243],
          [ 0.1653,  0.3548, -0.1084]]]])
torch.Size([32, 3, 3, 3])


In [12]:
class CNN(nn.Module):
    def __init__(self):
        super().__init__()

        self.conv1 = nn.Conv2d(1,8,6, stride=2)
        self.conv2 = nn.Conv2d(8,16,3,padding=1)
        self.Maxpool2 = nn.MaxPool2d(2)
        self.fc = nn.Linear(16*6*6,10)


    def forward(self,x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.Maxpool2(x)
        x = torch.flatten(x,start_dim=1)
        x = self.fc(x)
        return x

x = torch.randn(32,1,28,28)
model = CNN()
print(model(x).shape)

torch.Size([32, 10])


## .parameters() vs .modules() vs .children() 그리고 isinstance의 활용

In [13]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Sequential(nn.Linear(2,3),
                                 nn.ReLU())
        self.fc2 = nn.Sequential(nn.Linear(3,4),
                                 nn.ReLU())
        self.fc_out = nn.Sequential(nn.Linear(4,1),
                                    nn.Sigmoid())
    def forward(self,x):
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.fc_out(x)
        return x

model = MLP()
print(model(torch.randn(2,2)).shape)
print(model)

torch.Size([2, 1])
MLP(
  (fc1): Sequential(
    (0): Linear(in_features=2, out_features=3, bias=True)
    (1): ReLU()
  )
  (fc2): Sequential(
    (0): Linear(in_features=3, out_features=4, bias=True)
    (1): ReLU()
  )
  (fc_out): Sequential(
    (0): Linear(in_features=4, out_features=1, bias=True)
    (1): Sigmoid()
  )
)


In [14]:
list(model.parameters())
# [layer0 weight 값, layer0 bias 값, layer1 weight 값, layer1 bias 값, ...]

[Parameter containing:
 tensor([[-0.4127, -0.1224],
         [ 0.6640,  0.6872],
         [-0.1487,  0.5786]], requires_grad=True),
 Parameter containing:
 tensor([-0.3422,  0.2638,  0.1739], requires_grad=True),
 Parameter containing:
 tensor([[ 0.3346, -0.3864,  0.2877],
         [ 0.0257,  0.3128, -0.0977],
         [-0.0413, -0.5582, -0.5714],
         [ 0.2952, -0.2963, -0.0419]], requires_grad=True),
 Parameter containing:
 tensor([-0.1290,  0.0546, -0.3574, -0.4666], requires_grad=True),
 Parameter containing:
 tensor([[ 0.2649,  0.4443,  0.4271, -0.3192]], requires_grad=True),
 Parameter containing:
 tensor([-0.2783], requires_grad=True)]

In [15]:
# for tranfer learning 전이학습
model = MLP()

print([p for p in model.parameters() if p.requires_grad])

for p in model.parameters(): # 전체 Freeze
    p.requires_grad = False
model.fc_out = nn.Linear(4,10)

params = [p for p in model.parameters() if p.requires_grad]
print(params)

from torch import optim
optimizer = optim.Adam(params,lr=0.1)

[Parameter containing:
tensor([[ 0.5245,  0.5462],
        [ 0.0471,  0.0677],
        [-0.3159,  0.3492]], requires_grad=True), Parameter containing:
tensor([ 0.3544, -0.5963,  0.3959], requires_grad=True), Parameter containing:
tensor([[ 0.3449,  0.0454,  0.3725],
        [-0.0791,  0.0842, -0.3361],
        [-0.1533,  0.0997, -0.2495],
        [ 0.4162,  0.1582, -0.4964]], requires_grad=True), Parameter containing:
tensor([ 0.3610,  0.3769,  0.4476, -0.4019], requires_grad=True), Parameter containing:
tensor([[ 0.2855, -0.4679, -0.0107,  0.1085]], requires_grad=True), Parameter containing:
tensor([-0.1250], requires_grad=True)]
[Parameter containing:
tensor([[ 4.0148e-01,  9.2387e-02, -4.2127e-01,  6.7392e-02],
        [-3.6278e-01,  4.9424e-01,  1.9451e-01,  4.5797e-01],
        [-8.7256e-02,  3.4942e-01, -4.8083e-04,  4.1773e-01],
        [-2.1988e-01, -1.9984e-01,  2.9608e-01,  3.0073e-01],
        [ 3.8985e-01,  2.8407e-01,  3.1079e-01, -4.9668e-01],
        [ 1.9444e-01, -7.127

In [16]:
list(model.named_parameters())
# [('layer0.weight', weight 값), ('layer0.bias', bias 값), ('layer1.weight', weight 값), ('layer1.bias', bias 값), ...]

[('fc1.0.weight',
  Parameter containing:
  tensor([[ 0.5245,  0.5462],
          [ 0.0471,  0.0677],
          [-0.3159,  0.3492]])),
 ('fc1.0.bias',
  Parameter containing:
  tensor([ 0.3544, -0.5963,  0.3959])),
 ('fc2.0.weight',
  Parameter containing:
  tensor([[ 0.3449,  0.0454,  0.3725],
          [-0.0791,  0.0842, -0.3361],
          [-0.1533,  0.0997, -0.2495],
          [ 0.4162,  0.1582, -0.4964]])),
 ('fc2.0.bias',
  Parameter containing:
  tensor([ 0.3610,  0.3769,  0.4476, -0.4019])),
 ('fc_out.weight',
  Parameter containing:
  tensor([[ 4.0148e-01,  9.2387e-02, -4.2127e-01,  6.7392e-02],
          [-3.6278e-01,  4.9424e-01,  1.9451e-01,  4.5797e-01],
          [-8.7256e-02,  3.4942e-01, -4.8083e-04,  4.1773e-01],
          [-2.1988e-01, -1.9984e-01,  2.9608e-01,  3.0073e-01],
          [ 3.8985e-01,  2.8407e-01,  3.1079e-01, -4.9668e-01],
          [ 1.9444e-01, -7.1279e-02, -2.3233e-01,  4.4948e-01],
          [ 4.7809e-01, -1.7907e-01,  3.5499e-01,  4.0076e-01],
    

In [17]:
for name, p in model.named_parameters():
    print(name)
    print(p)

fc1.0.weight
Parameter containing:
tensor([[ 0.5245,  0.5462],
        [ 0.0471,  0.0677],
        [-0.3159,  0.3492]])
fc1.0.bias
Parameter containing:
tensor([ 0.3544, -0.5963,  0.3959])
fc2.0.weight
Parameter containing:
tensor([[ 0.3449,  0.0454,  0.3725],
        [-0.0791,  0.0842, -0.3361],
        [-0.1533,  0.0997, -0.2495],
        [ 0.4162,  0.1582, -0.4964]])
fc2.0.bias
Parameter containing:
tensor([ 0.3610,  0.3769,  0.4476, -0.4019])
fc_out.weight
Parameter containing:
tensor([[ 4.0148e-01,  9.2387e-02, -4.2127e-01,  6.7392e-02],
        [-3.6278e-01,  4.9424e-01,  1.9451e-01,  4.5797e-01],
        [-8.7256e-02,  3.4942e-01, -4.8083e-04,  4.1773e-01],
        [-2.1988e-01, -1.9984e-01,  2.9608e-01,  3.0073e-01],
        [ 3.8985e-01,  2.8407e-01,  3.1079e-01, -4.9668e-01],
        [ 1.9444e-01, -7.1279e-02, -2.3233e-01,  4.4948e-01],
        [ 4.7809e-01, -1.7907e-01,  3.5499e-01,  4.0076e-01],
        [ 3.5138e-01, -3.7035e-01, -1.1663e-01, -2.7497e-01],
        [ 3.0509e

In [18]:
model.modules()

<generator object Module.modules at 0x7c37c8e21ff0>

In [19]:
list(model.modules())

[MLP(
   (fc1): Sequential(
     (0): Linear(in_features=2, out_features=3, bias=True)
     (1): ReLU()
   )
   (fc2): Sequential(
     (0): Linear(in_features=3, out_features=4, bias=True)
     (1): ReLU()
   )
   (fc_out): Linear(in_features=4, out_features=10, bias=True)
 ),
 Sequential(
   (0): Linear(in_features=2, out_features=3, bias=True)
   (1): ReLU()
 ),
 Linear(in_features=2, out_features=3, bias=True),
 ReLU(),
 Sequential(
   (0): Linear(in_features=3, out_features=4, bias=True)
   (1): ReLU()
 ),
 Linear(in_features=3, out_features=4, bias=True),
 ReLU(),
 Linear(in_features=4, out_features=10, bias=True)]

In [20]:
print([m for m in model.modules() if isinstance(m,nn.Linear)])
print([m.weight for m in model.modules() if isinstance(m,nn.Linear)])
print([m.weight.grad for m in model.modules() if isinstance(m,nn.Linear)])

[Linear(in_features=2, out_features=3, bias=True), Linear(in_features=3, out_features=4, bias=True), Linear(in_features=4, out_features=10, bias=True)]
[Parameter containing:
tensor([[ 0.5245,  0.5462],
        [ 0.0471,  0.0677],
        [-0.3159,  0.3492]]), Parameter containing:
tensor([[ 0.3449,  0.0454,  0.3725],
        [-0.0791,  0.0842, -0.3361],
        [-0.1533,  0.0997, -0.2495],
        [ 0.4162,  0.1582, -0.4964]]), Parameter containing:
tensor([[ 4.0148e-01,  9.2387e-02, -4.2127e-01,  6.7392e-02],
        [-3.6278e-01,  4.9424e-01,  1.9451e-01,  4.5797e-01],
        [-8.7256e-02,  3.4942e-01, -4.8083e-04,  4.1773e-01],
        [-2.1988e-01, -1.9984e-01,  2.9608e-01,  3.0073e-01],
        [ 3.8985e-01,  2.8407e-01,  3.1079e-01, -4.9668e-01],
        [ 1.9444e-01, -7.1279e-02, -2.3233e-01,  4.4948e-01],
        [ 4.7809e-01, -1.7907e-01,  3.5499e-01,  4.0076e-01],
        [ 3.5138e-01, -3.7035e-01, -1.1663e-01, -2.7497e-01],
        [ 3.0509e-01,  2.5341e-01, -4.1289e-01, -

In [21]:
# weight initialization에 활용
for m in model.modules():
    if isinstance(m, nn.Linear):
        nn.init.kaiming_normal_(m.weight)
        # nn.init.constant_(m.weight, 1)

print([m.weight for m in model.modules() if isinstance(m, nn.Linear)])

[Parameter containing:
tensor([[ 0.4898,  0.8464],
        [-1.0636, -0.1774],
        [ 2.0708,  0.4033]]), Parameter containing:
tensor([[-0.3437,  0.6872, -0.8963],
        [ 0.6677,  0.5617, -0.5091],
        [-0.3303,  0.5462,  0.5473],
        [ 0.5520,  0.4006,  1.3460]]), Parameter containing:
tensor([[ 0.8032, -0.0838,  0.1237, -0.3734],
        [-0.1249, -1.8018,  0.0157, -0.0925],
        [-0.7789, -0.0807,  0.1498,  0.8130],
        [-0.0459,  0.2670,  0.4436,  0.9734],
        [-0.6591, -0.2078,  0.3098,  0.6460],
        [-0.8273,  0.6070, -1.0061,  0.9067],
        [ 0.1646,  0.3914,  0.0698,  0.6884],
        [ 1.2661, -0.4729, -0.6454,  1.1710],
        [ 0.3266, -1.4896, -0.3542,  0.2867],
        [-0.1280,  1.1503,  0.0801,  1.5340]], requires_grad=True)]


In [22]:
model.children()

<generator object Module.children at 0x7c37c8e22190>

In [23]:
list(model.children())

[Sequential(
   (0): Linear(in_features=2, out_features=3, bias=True)
   (1): ReLU()
 ),
 Sequential(
   (0): Linear(in_features=3, out_features=4, bias=True)
   (1): ReLU()
 ),
 Linear(in_features=4, out_features=10, bias=True)]

In [24]:
x = torch.randn(2,2)
list(model.children())[0](x)


tensor([[0.1229, 0.0000, 2.9780],
        [0.0000, 0.0000, 0.0000]])

In [25]:
print(*list(model.children())[:2])
sub_network = nn.Sequential(*list(model.children())[:2])
print(sub_network)
print(sub_network(x))

Sequential(
  (0): Linear(in_features=2, out_features=3, bias=True)
  (1): ReLU()
) Sequential(
  (0): Linear(in_features=3, out_features=4, bias=True)
  (1): ReLU()
)
Sequential(
  (0): Sequential(
    (0): Linear(in_features=2, out_features=3, bias=True)
    (1): ReLU()
  )
  (1): Sequential(
    (0): Linear(in_features=3, out_features=4, bias=True)
    (1): ReLU()
  )
)
tensor([[0.0000, 0.0000, 2.0370, 3.6744],
        [0.3610, 0.3769, 0.4476, 0.0000]])


## ModuleList vs Sequential

In [27]:
fc = nn.Linear(3,3)
layer_list = [fc for _ in range(5)]
layers1 = nn.Sequential(*layer_list)
layers2 = nn.ModuleList(layer_list)
print(layers1)
print(layers2)

x = torch.randn(1,3)
print(layers1(x)) # Sequential에는 forward 함수가 내장되어 있음

# print(layers2(x)) # error!

for layer in layers2:
    x = layer(x)

print(x)




Sequential(
  (0): Linear(in_features=3, out_features=3, bias=True)
  (1): Linear(in_features=3, out_features=3, bias=True)
  (2): Linear(in_features=3, out_features=3, bias=True)
  (3): Linear(in_features=3, out_features=3, bias=True)
  (4): Linear(in_features=3, out_features=3, bias=True)
)
ModuleList(
  (0-4): 5 x Linear(in_features=3, out_features=3, bias=True)
)
tensor([[ 0.2907, -0.0343,  0.1410]], grad_fn=<AddmmBackward0>)
tensor([[ 0.2907, -0.0343,  0.1410]], grad_fn=<AddmmBackward0>)


In [28]:
# 걍 리스트 쓰지 왜 nn.ModuleList 를 쓸까?
class testNet(nn.Module):
    def __init__(self):
        super().__init__()

        # self.Module_List = [nn.Linear(3,3), nn.Linear(3,3)]
        self.Module_List = nn.ModuleList([nn.Linear(3,3), nn.Linear(3,3)])

    def forward(self,x):
        for layer in self.Module_List:
            x = layer(x)
        return x

model=testNet()
print(model(torch.randn(1,3)))

print(model) # 그냥 리스트로 하면 등록이 안돼있다!

optimizer = optim.Adam(model.parameters(), lr = 0.1) # 등록이 안돼있으면 parameter를 못 찾는다

tensor([[-0.1933, -0.6687,  0.8490]], grad_fn=<AddmmBackward0>)
testNet(
  (Module_List): ModuleList(
    (0-1): 2 x Linear(in_features=3, out_features=3, bias=True)
  )
)


In [29]:
# 그럼 nn.Sequential 쓰고 말지 왜 굳이 nn.ModuleList?
class small_block(nn.Module):
    def __init__(self):
        super().__init__()
        self.block_x = nn.Linear(1,1)
        self.block_y = nn.Linear(1,1)

    def forward(self, x, y):
        x = self.block_x(x)
        y = self.block_y(y)
        return x, y

block = small_block()
print(block)
model = nn.Sequential(block, block)
print(model)
# model(torch.randn(1), torch.randn(1)) # error!
# nn.Sequential 이 가지고 있는 forward 함수를 call 하기 때문에 입력을 두 개 넣으면 안된다!!

model = nn.ModuleList([block,block])
x = torch.randn(1)
y = torch.randn(1)
for block in model:
    x, y = block(x,y)
print(x, y)

small_block(
  (block_x): Linear(in_features=1, out_features=1, bias=True)
  (block_y): Linear(in_features=1, out_features=1, bias=True)
)
Sequential(
  (0): small_block(
    (block_x): Linear(in_features=1, out_features=1, bias=True)
    (block_y): Linear(in_features=1, out_features=1, bias=True)
  )
  (1): small_block(
    (block_x): Linear(in_features=1, out_features=1, bias=True)
    (block_y): Linear(in_features=1, out_features=1, bias=True)
  )
)
tensor([1.0417], grad_fn=<ViewBackward0>) tensor([0.8087], grad_fn=<ViewBackward0>)
